---
title: "FastTopics For scNT-HH Dataset"
output:
  html_document:
    df_print: paged
---


```{r}
library(Matrix)
library(fastTopics)
library(ggplot2)
library(cowplot)
```

```{r}
#read in the count matrix
scNTHH_counts <- as(Matrix::readMM('scNT_HH_filtered_SU_Counts.mtx'), 'dgCMatrix')
dim(scNTHH_counts)
```
```{r}
#fit a topic model with 8 topics
K = 8
scNTHH_fit <- fit_topic_model(scNTHH_counts, k = K)
```
```{r}
#topic cell distributions
dim(scNTHH_fit$L)

#topic gene loadings
dim(scNTHH_fit$F)
```

```{r}
#Differential expression analysis
scNTHH_de <- de_analysis(scNTHH_fit, scNTHH_counts)
```

```{r}
#read in gene names
scNTHH_geneNames <- read.csv('scNT_HH_filtered_SU_Genes_names.csv', header = TRUE, stringsAsFactors=F)[[2]]
```


   
```{r}
#save the topic model and cell weights
saveRDS(scNTHH_fit, file='scNT_HH_fastTopics_fit.rds')
write.csv(scNTHH_fit$L, file='scNT_HH_fastTopics_fit_CellWeights.csv')

#save the differential expression analysis
saveRDS(scNTHH_de, file='scNT_HH_de.rds')
write.csv(scNTHH_de$postmean, file='scNT_HH_de_postmean.csv')
write.csv(scNTHH_de$lfsr, file='scNT_HH_de_lfsr.csv')
write.csv(scNTHH_de$z, file='scNT_HH_de_z.csv')
```






