---
title: "FastTopics For scNT-HH Dataset"
output:
  html_document:
    df_print: paged
---


```{r}
library(Matrix)
library(fastTopics)
```

```{r}
#read in the count matrix
scNTHH_counts <- as(Matrix::readMM('data/scNT-seq/scNT_HH_filtered_SU_Counts.mtx'), 'dgCMatrix')
#read in gene names
scNTHH_geneNames <- read.csv('data/scNT-seq/scNT_HH_filtered_SU_Genes_names.csv', header = TRUE, stringsAsFactors=F)[[2]]
```

```{r}
#fit a topic model with n topics
Ks <- c(8)
for (K in Ks) {
  scNTHH_fit <- fit_topic_model(scNTHH_counts, k = K)
  #Differential expression analysis
  scNTHH_de <- de_analysis(scNTHH_fit, scNTHH_counts)
  
  #save the topic model and cell weights
  saveRDS(scNTHH_fit, file=paste("data/scNT-seq/scNT_HH_fastTopics_fit_k=", K,'.rds',sep=""))
  write.csv(scNTHH_fit$L, file=paste("data/scNT-seq/scNT_HH_fastTopics_fit_CellWeights_k=", K,'.csv',sep=""))
  #save the differential expression analysis
  saveRDS(scNTHH_de, file=paste("data/scNT-seq/scNT_HH_de_k=", K,'.rds',sep=""))
  write.csv(scNTHH_de$postmean, file=paste("data/scNT-seq/scNT_HH_de_postmean_k=", K,'.csv',sep=""))
  write.csv(scNTHH_de$lfsr, file=paste("data/scNT-seq/scNT_HH_de_lfsr_k=", K,'.csv',sep=""))
  write.csv(scNTHH_de$z, file=paste("data/scNT-seq/scNT_HH_de_z_k=", K,'.csv',sep=""))
}
```








